import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import Fab from "./_components/fab";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const backgrounds = [
    "/images/climb.png",
    "/images/forest.png",
    "/images/mountains.png",
    "/images/sea.png",
    "/images/stars.png",
  ];

  const randomIndex = Math.floor(Math.random() * backgrounds.length);
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="overflow-hidden bg-background">
        <TRPCReactProvider>
          <main
            className="relative flex min-h-screen overflow-hidden text-white"
            style={{
              backgroundImage: `url(${backgrounds[randomIndex]})`,
              backgroundSize: "cover",
              backgroundPosition: "center",
            }}
          >
            {children}
            <Fab />
          </main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
