"use client";

import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { useState } from "react";
import { TRPCReactProvider } from "~/trpc/react";
import ActivitySwatch from "./_components/activitySwatch";
import Fab from "./_components/fab";

// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const backgrounds = [
    "/images/climb.png",
    "/images/forest.png",
    "/images/mountains.png",
    "/images/sea.png",
    "/images/stars.png",
  ];

  const [isActivitySwatchOpen, setIsActivitySwatchOpen] = useState(false);

  const [randomIndex] = useState(
    Math.floor(Math.random() * backgrounds.length),
  );
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="overflow-hidden bg-background">
        <TRPCReactProvider>
          <main
            className="relative flex min-h-screen overflow-hidden text-white"
            style={{
              backgroundImage: `url(${backgrounds[randomIndex]})`,
              backgroundSize: "cover",
              backgroundPosition: "center",
            }}
          >
            {children}
            <Fab
              isActivitySwatchOpen={isActivitySwatchOpen}
              setIsActivitySwatchOpen={() =>
                setIsActivitySwatchOpen((prev) => !prev)
              }
            />
            <ActivitySwatch isOpen={isActivitySwatchOpen} />
          </main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
